# Generated by Django 4.0.3 on 2022-04-20 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transactions',
            new_name='Transaction',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user',
            new_name='name',
        ),
    ]
