# Generated by Django 4.0.3 on 2022-04-27 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_api', '0002_rename_transactions_transaction_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Points',
        ),
        migrations.RenameField(
            model_name='points',
            old_name='name',
            new_name='payer',
        ),
    ]
