# Generated by Django 4.0.3 on 2022-04-27 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_api', '0003_rename_user_points_rename_name_points_payer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transaction',
            new_name='Transactions',
        ),
    ]
