# Generated by Django 4.0.3 on 2022-04-27 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_api', '0005_alter_points_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='payer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise_api.points', to_field='payer'),
        ),
    ]
