# Generated by Django 4.0.3 on 2022-04-27 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_api', '0006_alter_transactions_payer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='payer',
            field=models.CharField(max_length=30),
        ),
    ]
